Repository tech-harmony-team/Jibun-Log, pull requests merged in 2024-07, with the labels that each got.

#13 【FE】ユーザーデータをCookieに保存したり取得できたりするようにした。
  next-front/package-lock.json
  next-front/package.json
  next-front/src/app/cookie-test/page.tsx
  next-front/src/hooks/useUserDatas.tsx
  next-front/src/types/userData.ts
Labels: frontend, priority, common

#15 RailsのDeviseを使って、Userのモデルを作成
  rails-api/Gemfile
  rails-api/Gemfile.lock
  rails-api/app/controllers/application_controller.rb
  rails-api/app/models/user.rb
  rails-api/config/initializers/devise.rb
  rails-api/config/initializers/devise_token_auth.rb
  rails-api/config/locales/devise.en.yml
  rails-api/config/routes.rb
  rails-api/db/migrate/20240727061652_devise_token_auth_create_users.rb
  rails-api/db/schema.rb
Labels: backend

#17 【FE #8】ヘッダーのUIコンポーネントを作成した。
  next-front/src/app/header-test/page.tsx
  next-front/src/components/typography/pageHeader.tsx
Labels: frontend, priority, common

#19 【FE #7】日記一覧画面のレイアウトのみ作成した。
  next-front/src/app/diary/page.tsx
  next-front/src/app/globals.css
  next-front/tailwind.config.js
Labels: frontend

#20 【FE #4】ホーム画面を作成した＋a
  next-front/src/app/home/page.tsx
  next-front/src/app/page.tsx
Labels: frontend

#39 【FE #5】新規登録画面とログイン画面を作成した
  next-front/src/app/auth/page.tsx
  next-front/src/app/sign-in/page.tsx
Labels: frontend

#24 【FE】日記を一覧表示するカードコンポーネントを作成した。
  next-front/src/app/diary/page.tsx
  next-front/src/components/daiary-card/diaryCard.tsx
  next-front/src/types/daiaryData.ts
  next-front/tailwind.config.js
Labels: frontend, priority, common

#45 【FE #35】GPTを使って、質問を作らせるサンプルを作った。
  next-front/src/app/test-create-q/page.tsx
  next-front/src/hooks/useChatGpt.tsx
Labels: frontend
